### ISSUE TITLE
MATLAB version is much faster

### ISSUE THREAD

**Issue by araujoms** [jump-dev/SCS.jl#262]
As I wrote in jump-dev/MathOptInterface.jl#2124, the default installation on MATLAB is much faster than the default installation in Julia. The issue seems to be that in MATLAB SCS uses the MKL Pardiso linear solver by default (even though it's called simply `sparse-direct`), whereas in Julia SCS.jl uses the ADM QDLDL solver by default (called `sparse-direct-amd-qdldl`).

I've added the MKL Pardiso solver in Julia (called `sparse-direct-mkl-pardiso`), and indeed with it I achieve the same performance as MATLAB. Surely it must be possible to use the faster solver by default in Julia as well.

**Comment by araujoms** [comment]
I don't see the problem. Storage is cheap. And the whole point of SCS is tackling those monstrous problems where performance really matters. If I have a small problem I will use a second-order solver that gives me higher accuracy.

I also don't understand why is linking against MKL in MATLAB a separate issue. Are you implying that I would get even higher performance with Julia if I switched to another blas?

**Comment by kalmarek** [comment]
It's a separate issue cause it adds another degree of freedom when comparing with MATLAB;
If I remember correctly SCS uses only blas-1 functions which are memory-bound; If so, it's unlikely to get significantly better performance by switching to a different blas.

I'm not sure what is the problem you are reporting here:
* SCS.jl uses the small, self-contained sparse-direct solver by default;
* SCS.jl allows you to opt-in into using MKL Pardiso solver, as designed;

If you want to change the default please read below.

----

All of those factors were taken into the account while deciding against shipping the mkl-based solver as default:
 * users can access the mkl-based solver by inserting a single line of code;
 * defaulting to the mkl-based solver causes the package size to grow by a factor of ~1000;
 * whether the mkl-based solver is much faster is very much problem-dependent;

The problem is not storage. The problem we see is the imbalance between library size and the supposed dependency. Similarly, since CUDA is not essential to the function of `SCS.jl`, we don't require users to download another few GB of cuda libs.

**Comment by araujoms** [comment]
The problem is precisely what I had written: the MATLAB version is much faster. Having different defaults depending on the interface used is at least confusing. Intentionally using an inferior default is just bizarre. Package size does not matter.

CUDA is a different matter, many users don't need it. The linear solver is the heart of SCS.

**Comment by kalmarek** [comment]
I'm confused by the title right now.
A version of __what__ in MATLAB is much faster?
Is there a function provided by both MATLAB and SCS.jl that is faster in the former?
Could you provide more details with MWE?
Is it uniformly faster or is it just faster on your example?

If you don't agree with my diagnosis of the problem (since you deemed the title inappropriate) I'd appreciate if you could change the title to an informative one, based on the answers to the questions above.

I will not argue whether the choice of default solver is _confusing_: it is a subjective opinion. I understand that this choice could be _surprising_ to you. The default linear solver is however [**described** in the README](https://github.com/jump-dev/SCS.jl#linear-solvers). If you find the **description** confusing, please provide a suggestion how could we describe the default in less confusing terms.

We clearly have different opinions on size ;)

**Comment by araujoms** [comment]
Clearly there's no information left to exchange, and no point in arguing.

**Comment by odow** [comment]
Just to echo @kalmarek: we won't be shipping the MKL linear solver as default in SCS.

If we're installing something that is 1.4Gb, I think we want that to be opt-in, not always on with no opt-out. MATLAB are in a different position, because they can support a single large install.

There's a similar issue in Ipopt: https://github.com/jump-dev/Ipopt.jl#linear-solvers, https://github.com/jump-dev/Ipopt.jl/issues/6.

**Comment by araujoms** [comment]
Only now I've realized that MKL is proprietary software, and the MKL package is just a binary blob (which is why it's so big). So no, of course it shouldn't be included by default.
